apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  labels:
    k8s-app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      labels:
        k8s-app: registry
    spec:
      containers:
        - env:
            - name: connectionInfo_password
              value: opensaber
            - name: connectionInfo_uri
              value: jdbc:postgresql://sunrc-postgres-postgresql.default.svc.cluster.local:5432/registry
            - name: connectionInfo_username
              value: opensaber
            - name: sunbird_sso_publickey
              value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlg8dR/09kQ4tybLbyHSx2oKWstxSEIhkYx7vC+9dQkgmu83E8331/N67tr1CbbxvSEcQ1VXE+3AG9dm3JE3o6ltD0TMXBbtE9bXJFdS/abVoJ6F6A7rY3LaQY9FG7ZmCjUfGweN3BfUWR+u+lMUUAVrzOdrqavMmbsE/orvujgzEXUinXIBBYZGXxhGNQqLIrNVjSaD3sgO3ne1WNYkaJH+ZcIRU0Y7NELq3djuyHRmf0uqNr4E+YCpBi2Vh69+CY8WnVVFfdIGXMWUsFnIY9nRTIP4uduBSMWMzhkQ4IqjeO5ACxqGuOIDYLwjft0MnPmFB0OO/fyWQbzjHlvOASQIDAQAB
            - name: sunbird_sso_realm
              value: sunbird-rc
            - name: sunbird_sso_url
              value: http://10.96.229.158:30009/auth
            - name: sunbird_sso_admin_client_id
              value: admin-api
            - name: sunbird_sso_client_id
              value: registry-frontend  
            - name: sunbird_sso_admin_client_secret
              value: 15b0e3fd-f57e-4d8e-94ac-f97d7c4a0b61
            - name: claims_url
              value: http://claim-ms:8082
            - name: search_providerName
              value: io.opensaber.registry.service.ElasticSearchService 
            - name: elastic_search_connection_url
              value: elasticsearch-1635580419-coordinating-only.default.svc.cluster.local:9200
            - name: filestorage_connection_url
              value: none
            - name: filestorage_access_key
              value: none
            - name: filestorage_secret_key
              value: none
            - name: filestorage_bucket_key
              value: none
          image: dockerhub/opensaber-rc:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
#            limits:
#              cpu: 500m
          name: registry
          ports:
            - containerPort: 8081
      restartPolicy: Always


