apiVersion: v1
data:
  prom-add.yaml: LSBqb2JfbmFtZTogImpteF9taWNyb18xX3Byb21ldGhldXMiCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbIjEwLjk2LjEwLjEyMzo4MDgwIl0K
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
