apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-microsvc-static-1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-microsvc-static-1
  minReplicas: 1
  maxReplicas: 10
  #targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage: 90
  metrics:
  # - type: Resource
  #  resource:
  #    name: cpu
  #    target:
  #      type: Utilization
  #      averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 20
