apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-for-kong
  annotations:
    #konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /microsvc-static1/health  #*
        backend:
          serviceName: microsvc-static1
          servicePort: 7050
      - path: /microsvc-static1/callOtherService
        backend:
          serviceName: microsvc-static1
          servicePort: 7050
      - path: /microsvc-static2/health
        backend:
          serviceName: microsvc-static2
          servicePort: 7051
      - path: /microsvc-static2/callOtherService
        backend:
          serviceName: microsvc-static2
          servicePort: 7051
