apiVersion: v1
kind: Service
metadata:
  name: svc-microsvc-static-1
spec:
  selector:
    app: deploy-microsvc-static-1
  ports:
    - protocol: TCP
      port: 7050
      targetPort: 7050
  clusterIP: 10.124.80.19
  type: ClusterIP 
