apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  namespace: ns-monitoring
  labels:
    type: local
spec:
  claimRef:
    name: promstack-grafana
    namespace: ns-monitoring
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/graf-store
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
