apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: promstack-grafana
    namespace: monitoring
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # *****not for production
    path: "/opt/mount-data"
  #gcePersistentDisk:
  #  fsType: ext4
  #  pdName: my-data-disk
