apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prom-storage
  labels:
    app: pv-prom-storage
    type: local
spec:
  claimRef:
    name: prometheus-promstack-kube-prometheus-prometheus-db-prometheus-promstack-kube-prometheus-prometheus-0
    namespace: ns-monitoring
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /data/prom-store
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
