apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prom-storage
  namespace: monitoring
  labels:
    app: pv-prom-storage
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: ""
  claimRef:
    name: prometheus-promstack-kube-prometheus-prometheus-db-prometheus-promstack-kube-prometheus-prometheus-0
    namespace: monitoring
  accessModes:
  - ReadWriteOnce # required
  hostPath: # *****not for production
    path: "/opt/prom-store"
  
