apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-vol-claim
  namespace: ingress-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
