apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-vol
  namespace: ingress-nginx  
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: persistent-vol-claim
    namespace: ingress-nginx
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  #hostPath: # *****not for production
  #  path: "/opt/mount-data"
  gcePersistentDisk:
    fsType: ext4
    pdName: my-data-diski  ### create disk and attch to vm transfer files and detach VM and attach here
